version: '3.8'

services:
  db:
    image: mongo:${MONGO_VERSION}
    restart: always
    container_name: db
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - net_A

  server:
    image: karolwisniewski/server
    container_name: server
    restart: always
    ports:
      - 3003:3000
    depends_on:
      - db
    networks:
      - net_A

networks:
  net_A:

volumes:
  mongo_data:
