version: '3.8'

services:
  web:
    depends_on:
      - db
    container_name: web
    build: ./web
    ports:
      - "80:80"
    networks:
      - my_network

  db:
    container_name: db
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network: {}